---
title: "HW-3"
author: "Alexa Andrade"
format: html
editor: visual
link to github repositroy: https://github.com/Alex2002UC/ENVS-193DS_homework-03 
excecute:
 warning: false
 message: false
---

```{r}
#Read in packages 
library(tidyverse)
library(here)
library(gt)

install.packages("flextable")
library(flextable)
library(janitor)

install.packages("readxl")
library(readxl)

```

\## Part 2. Problems

### Problem 1. Personal data (30 points)

::: callout-note
Before doing this problem, update your spreadsheet with your new observations. Save your data as a .csv or .xlsx in your \`data\` folder.
:::

#### a. Data summarizing (5 points)

In 1-2 sentences, describe how you could summarize your data to compare your response variable between categories or groups of your choosing. For example, are you counting observations and comparing counts between groups? Are you taking the mean and comparing means between groups? Are you finding the maximum, minimum, range? Are you adding numbers together?

Be sure to describe \_why\_ comparing between the groups you chose is informative. For example, you might calculate the mean number of steps you take to compare between week days, but what about those weekdays is \_different\_ (e.g. "I could calculate the mean number of steps I took to compare average step count between weekdays because I have more classes on Monday than on any other day of the week, so I think I walk more on Monday.")

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

#### b. Visualization (10 points)

Using the summary you described in part a, \*\*create a visualization of your data comparing your summarized response variable between groups\*\*. If you are calculating a mean or median, show the underlying data in addition to your summary.

Use colors in your figure (that are not the default ggplot settings).

Make sure your axis labels are full, readable text (not just your column names).

::: callout-note
See \[From Data to Viz\](https://www.data-to-viz.com/) for new ideas for visualization.
:::

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

#### c. Caption (5 points)

Write a \_caption\_ for your figure.

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

#### d. Table presentation (10 points)

Using \`gt\` or \`flextable\`, create a table with the same data summary that you describe in part a and visualized in part b. For example, if you described and visualized means, make a table with means. If you need to, round any numbers to one decimal point.

Display the output.

::: callout-tip
Try \_rendering\_ your document here! Commit and push your changes, then find the url to your rendered output (if you get stuck, see the video on Canvas and/or the Git/GitHub basics page under the "Resources" tab).

Double check that your rendered document looks the way you would expect (e.g. tables all correct, text is formatted correctly). If not, go back and fix any issues or ask for help.
:::

### Problem 2. Affective visualization (24 points)

In this problem, you will create an \*\*affective visualization\*\* using your personal data in preparation for workshops during weeks 9 and 10.

In lecture, we talked about the three vertices of data visualization: 1) exploratory, 2) affective, and 3) communicative. We've done a lot of exploratory and communicative visualization, but have yet to think about affective visualization.

When thinking of affective visualization, you can expand your ideas of what data visualization \_could\_ be. Some examples of affective visualizations include:

-   \[Jill Pelto's paintings\](https://www.jillpelto.com/gallery-1)
-   \[Lorraine Woodruff-Long's warming strips quilt \](https://www.instagram.com/p/C689Kybxget/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==)
-   \[Stefanie Posavec and Giorgia Lupi's Dear Data project\](https://www.dear-data.com/all)
-   \[Environmental Graphiti\](https://www.environmentalgraphiti.org/series-folder)

#### a. Describe in words what an affective visualization could look like for your personal data (3-5 sentences). (2 points)

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

#### b. Create a sketch (on paper) of your idea. (2 points)

Include a photo of this sketch in your submission.

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.

Double check your rendered URL to make sure the photo of your sketch shows up.
:::

#### c. Make a draft of your visualization. (12 points)

Feel free to be creative with this! \_You do not have to do this in R.\_ You could create a sculpture, painting, textile object, etc.

If you are making your visualization in R, show the annotated code and the output.

If you are making your visualization outside of R, include a photo of your visualization in your submission.

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.

If you are including a photo, double check your rendered URL to make sure the photo of your draft shows up.
:::

#### d. Write an artist statement. (8 points)

An artist statement gives the audience context to understand your work. For each of the following points, write 1-2 sentences to address:

-   the content of your piece (what are you showing?)
-   the influences (what did techniques/artists/etc. did you find influential in creating your work?)
-   the form of your work (written code, watercolor, oil painting, etc.)
-   your process (how did you create your work?)

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

::: {.callout-note title="This is prep for workshop during week 9!"}
During week 9, we will send time providing peer review for your affective visualization. If you turn in your homework next Wednesday, you will have a draft of your affective visualization that is ready for peer review.
:::

### Problem 3. Statistical critique (36 points)

At this point, you have seen and created a lot of figures for this class. Revisit the paper you chose for your critique and your homework 2, where you described figures or tables in the text. Address the following in full sentences (3-4 sentences each).

\*\*For this section of your homework, you will be evaluated on the logic, conciseness, and nuance of your critique.\*\*

#### a. Revisit and summarize (6 points)


A two-tailed Student’s t-test and a two-way mixed AVOLVA was conducted to answer the author's main research question: : Could mammalian cells retain a faithful copy of epigenetic information from earlier in life, which could serve as a guide in reversing aging? The response variable was axon regeneration and axon density, while the predictor variable was drug treatment of intravitreal injection of Adeno-Associated-Viruses that delivered OSK genes into the mice.The two-tailed student t-test was used to compare axon density and retinal ganglion counts between OSK gene-treated groups, so a significant result of a p-value less than 0.05 would mean that the OSK treatment led to reliable regeneration of axon density, supporting the paper’s hypothesis that epigenetic reprogramming can help reverse vision loss.


Insert the figure or table you described in Homework 2 here.


::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

#### b. Visual clarity (10 points)



  THe authors did a clear job of logically labelling their axis and different control and treatment groups with color. However, the positioning of the p-values above the graph makes it unclear which p-value is for which comparison. The figure does show mean with Standard error bars, with the underlying data points being displayed for visual clarity.


::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

#### c. Aesthetic clarity (10 points)


I believe the authors handelled their visual clutter moderately well, as they ensured their were no background lines or grids that weren't actively symbolizing data. However, the data:ink ratio is not as maximized as it could be, with the P-values from the comparisons between the groups being unessessarily underlined and larger than what I think is reasonable, adding more ink to the figure while not adding more information about the data. 


::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

#### d. Recommendations (can be longer than 4 sentences, 10 points)

What recommendations would you make to make the figure or table better? What would you take out, add, or change? Provide explanations/justifications for each of your recommendations.

\*\*Alternatively\*\*, if they did not represent their statistics in a figure, what kind of figure would you recommend to them? Describe the x- and y-axes, with any geometries and aesthetics (colors, etc.). Provide enough explanation such that someone would be able to create the figure you describe in code. Provide explanations/justifications for the figure you would recommend.

::: callout-tip
Try committing and pushing your changes here! Write an \_informative\_ commit message.
:::

## 
